### ISSUE TITLE
A few thoughts

### ISSUE THREAD

**Issue by TrueV** [kexanie/MathView#1]
Hey there, 
first of all, thank you for the great work putting this together as it will come in pretty handy for me further on, because I have no idea how to get MathJax working in my App.

Well, I noticed a few things, where you can perhaps help me with:

1. I made an MathView Element in my XML file and tested the performance of the rendering, which was noticeable slow. Is this a problem occurring also with MathJax as a standalone version? - If not, is there a way to speed up the render process?
2. Do you have a documentation about the usable functions and how to implement them?
(Can I just use this for reference?: http://meta.math.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference )
3. Could you give an example for using MathJax in Java to render variables coming from, for example, Strings?

Greetings

**Comment by kexanie** [comment]
Hi TrueV,
thank you for your feedback. About the questions you posted.

1. I suppose the bottleneck is MathJax itself. In order to [shrink] the size of MathJax, I limited the output to be HTML rather than SVG, usually the latter is ~25% faster. [This document] gives an overview of the different aspects that affect MathJax performance as well as several potential development options to improve performance. 
2. I haven't done a thorough test, but I think it's OK to use it for reference except that, to insert inline formua, you should use `\(...\)` rather than the dollar sign notation.
3. I've update the readme document, please have a look on it.

Anyway, this lib is still rather primitive. Thank you for your attention. Pull Requsts are always welcome. :)

[This document]: https://github.com/mathjax/MathJax/wiki/Understanding-mathjax-performance
[shrink]: https://github.com/mathjax/MathJax-grunt-cleaner
