### ISSUE TITLE
Automatic line breaking

### ISSUE THREAD

**Issue by vyndor** [kexanie/MathView#10]
MathJax have an option for automatic linebreaking.
http://mathjax.readthedocs.org/en/latest/output.html#automatic-line-breaking
It is a very useful feature for small viewports and large expressions. Can I enable it somehow in MathView?

**Comment by kexanie** [comment]
Hmm, I am not an expert in MathJax. Rather than providing a pre-configured version of MathJax, I choose to add another method `config()` to `MathView` in version `0.0.5`.

Now you can try call 
```java
MathView.config(
"MathJax.Hub.Config({\n"+
            "  CommonHTML: { linebreaks: { automatic: true } },\n"+
            "  \"HTML-CSS\": { linebreaks: { automatic: true } },\n"+
            "         SVG: { linebreaks: { automatic: true } }\n"+
            "});");
```
before the `setText()` method to enable auto linebreaking. Please try upgrade to version `0.0.5` and see if this works for you!
